- include/am-thread-posix.h
We currently leak threads if Join() is never called (such as IThreader threads using Thread_AutoRelease or the simple MakeThread overload). Also, calling Join() more than once could cause a crash / the wrong thread to be joined. This changes the POSIX thread implementation to match the behaviour of the Windows one and let the OS clean up resources if the Thread instance is released.
@dvander
> POSIX threading fixes

- amtl/os/am-shared-library.h
ke::SharedLib will crash on linux (maybe posix) if it can't find/open the library. This adds a branch in the destructor to prevent such an occurrence.
#0  0xf7ff08d7 in ?? () from /lib/ld-linux.so.2
No symbol table info available.
#1  0xf7f80dd2 in ?? () from /lib/libdl.so.2
No symbol table info available.
#2  0xf7feaf56 in ?? () from /lib/ld-linux.so.2
No symbol table info available.
#3  0xf7f8138c in ?? () from /lib/libdl.so.2
No symbol table info available.
#4  0xf7f80e08 in dlclose () from /lib/libdl.so.2
No symbol table info available.
#5  0xea6e6a48 in ke::SharedLib::~SharedLib (this=0x83ef5c0, __in_chrg=<optimized out>) at /home/plagueshell/sourcemod/public/amtl/amtl/os/am-shared-library.h:74
No locals.
> dlclose crashes when given NULL.

- amtl/am-allocator-policies.h
- amtl/am-deque.h
- amtl/am-fixedarray.h
- amtl/am-hashtable.h
- amtl/am-linkedlist.h
- amtl/am-vector.h
- tests/runner.h
When compiling something with the CRT memory leak detection enabled on debug builds, MSCV compile errors due to free and malloc being defines.
> Fix AMTL against CRT library memory leak detection on debug builds.

- amtl/am-cxx.h
From:
https://msdn.microsoft.com/en-us/library/hh409293.aspx?f=255&MSPPError=-2147217396#BK_Compiler
constexpr Create compile-time constant variables, functions and
user-defined types. (C++11)
noexcept The noexcept operator can now be used to check whether an
expression might throw an exception. The noexcept specifier can now be
used to specify that a function does not throw exceptions. (C++11)
Note: Left in constexpr check for a specific VS version as the VS 2013 community edition I have installed doesn't support constexpr
> VS 2015 has support for constexpr and noexcept

- AMBuildScript
- README.md
- amtl/am-function.h
- amtl/am-thread-posix.h
- amtl/am-thread-windows.h
- tests/test-callable.cpp
C++14 allows us to capture lambda variables, via syntax like this:
auto lambda = [var = std::move(thing)] () -> void { ... }
However, AMTL's `Lambda` implements a copy constructor. Since it must delegate the copy to a virtual base class, the compiler has no way of automatically excluding this copy. If you capture something like AMTL's `Vector`, the compiler will error, even if done by move assignment. For example,
Vector<int> v;
Lambda<void()> f = [v = Move(v)]() -> void {};
Will fail, because the AMTL wrapper for the compiler-generated lambda type must implement a virtual copy function. STL suffers from the same problem; this will not compile:
std::unique_ptr<int> p = std::make_unique<int>(5);
std::function<void()> f = [p = std::move(p)] () -> void {};
There are two ways I guess we could …
> Introduce a third Lambda variant.

- amtl/am-priority-queue.h
- tests/AMBuild.tests
- tests/test-priority-queue.cpp
This is a super simple wrapper around Vector, implementing a priority queue using a binary heap. I think we intended to have something like this for SM or AMXX tasks ages ago, but never got around to it.
> Add a simple priority queue.

- amtl/am-deque.h
- amtl/am-fixedarray.h
- amtl/am-hashmap.h
- amtl/am-hashset.h
- amtl/am-hashtable.h
- amtl/am-linkedlist.h
- amtl/am-vector.h
- tests/test-linkedlist.cpp
- tests/test-vector.cpp
While playing around I ran into a nasty bug:"
Vector<int> v1;
Vector<float> v2(Move(v1));
This does not error in AMTL. Instead it triggers v1 coercing to an AllocPolicy, which matches v2's empty constructor. Super bad.
This patch fixes it by making AllocPolicy inheritance private on all our containers. Since this removes coercion to AllocPolicy, I added explicit accessors in a few places.
> Fix constructors of different types coercing to AllocPolicy.

- amtl/am-algorithm.h
- amtl/am-cxx.h
- amtl/am-priority-queue.h
- tests/test-callable.cpp
Until all our AppVeyors are updated, we should keep MSVC2013 support. Use of generic lambda captures and constexpr is now compile-time tested.
> Fix MSVC2013 support.

- amtl/am-hashtable.h
This is a reworked patch from https://bugs.alliedmods.net/show_bug.cgi?id=6527 .
At the moment HashTable::lookupForAdd will break on it's search if a single entry has been removed, resulting in multiple unique entries being present in SourceMod's StringHashMap. HashTable::lookup instead checks if the entries are free.
This has multiple drawbacks that I'm assuming this was supposed to account for, such as effectively defragging the hashtable when a new entry is inserted. The real fix is to do a full lookup, and if the hash is not present; insert on the first "removed" entry. If we want to do this full scan or not to ensure there are no collisions is unknown to me.
> Fix am-hashtable lookupForAdd not scanning past removed entries from the probulator (bug 6527).

- README.md
- amtl/am-autoptr.h
- amtl/am-string.h
- amtl/am-type-traits.h
- tests/AMBuild.tests
- tests/test-autoptr.cpp
AutoPtr is roughly unique_ptr from C++11. These patches bring it more in-line with C++14.
1. `AutoArray` is removed. `AutoArray<T>` should now be written as `AutoArray<T[]>`.
1. `AutoPtr<T[]>` no longer has raw pointer assignment through `operator =`.
1. An overload for `operator []` is provided again. It was removed in PR #12, but we no longer support the problematic compiler there (GCC 4.5).
1. `MakeUnique` is provided as a straight copy of C++14's `make_unique`.
The standard library also has a "deleter" feature that is somewhat akin to PR #8. This looks like it introduces a lot of complexity and AM hasn't needed it yet, so I left that out for now.
> Modernize AutoPtr.

- amtl/am-autoptr.h
- amtl/am-string.h
This removes two kind of unsafe features of AutoPtr. First, cast-to-T makes `operator *` confusing. It's easy to do the wrong dereference. Second, assign-from-T* makes it too easy to implicitly adopt pointers that maybe shouldn't be adopted.
We'll see how this plays out with AM code - if things become too gross I will back this out.
> Remove AutoPtr implicit cast-to-T and assign-from-T*.

- README.md
- amtl/am-autoptr.h
- amtl/am-uniqueptr.h
- tests/AMBuild.tests
- tests/test-autoptr.cpp
- tests/test-uniqueptr.cpp
The AutoPtr changes were too aggressive for AM code, SourceMod started to look ugly. Instead, I reverted AutoPtr and copied the new version to UniquePtr.
> Move AutoPtr changes to new UniquePtr class.

- amtl/am-hashset.h
Should call the equivalent function in HashTable.
> Fix HashSet::removeIfExists proxying wrong method

- tests/main.cpp
- tests/test-autoptr.cpp
The testrunner main() always returned 0 even if there was a test
failing. Travis will now correctly indicate the build as failed, if
there is a test broken.
> Fix AutoPtr tests and indicate failed tests in return value

- amtl/am-inlinelist.h
Fix for pre increment ```InlineList``` iterator. I believe it's just a typo.
> Fix inlinelist pre increment iterator

- amtl/os/am-system-errors.h
A typo lead to always just writing "error code %08x" if FormatMessage was successful.
> Fix getting system error message on windows

- amtl/am-hashmap.h
- amtl/am-hashset.h
- amtl/am-hashtable.h
- tests/test-callable.cpp
Allow nesting HashTable types and friends inside each other.
```cpp
typedef ke::HashSet<void*, ke::PointerPolicy<void>> NiceSet;
typedef ke::HashMap<int, NiceSet, IntegerPolicy> AwesomeMap;
```
That's your code @dvander 🥇
> Add move constructor to HashTable, HashSet and HashMap

- .gitignore
- AMBuildScript
- README.md
- amtl/am-cxx.h
- amtl/am-enum.h
- amtl/am-flags.h
- tests/AMBuild.tests
- tests/test-flags.cpp
Explanation is in README.md. This is meant to solve the following pattern, since C++ does not have any way to make scoped enums implicitly convertible to bool:
```
enum class Blah {
None = 0,
Flag1 = 0x1
};
Blah flags = Blag::None;
if (!!flags) ...
```
We can now use:
```
enum class Blah {
None = 0,
Flag1 = 0x1
};
Flags<Blah> flags = Blag::None;
if (!flags) ...
```
This patch also fixes a bug where `KE_DEFINE_NUM_OPERATORS` assumed the enum fields fit in `uint32_t`.
> Add a new Flags<T> wrapper for scoped enumerations that contain bitwise flags.

- AMBuildScript
- amtl/am-string.h
- amtl/am-uniqueptr.h
- tests/test-string.cpp
This adds `Sprintf` and `SprintfArgs` which will return a `UniquePtr<char[]>` containing the formatted string. It's intended for cases where a `SafeSprintf` truncating is not desirable. There are also `AString` variants as well.
In addition this patch removes an `AutoPtr` instance.
> Add sprintf functions that will allocate a best-fit buffer.

- amtl/am-string.h
Looks like _vsnprintf() returns -1 if it can't fill the buffer. Luckily Fyren pointed out _vscprintf().
> Fix Sprintf() on Windows.

- README.md
- amtl/am-string.h
- amtl/experimental/am-argparser.h
- tests/AMBuild.tests
- tests/test-argparser.cpp
This is not the most glamorous utility class but it will help make our command-line tools a lot prettier. It does not support repeated arguments or trailing arguments (yet), so ironically I didn't use it in AMTL's testrunner. The first consumer will be spshell.
> Add a simple command-line argv parser, similar to Python's argparse.

- amtl/experimental/am-argparser.h
- tests/test-argparser.cpp
And this is why argparser is "experimental". Having to type `Option<IntValue>` is weird, and I didn't fully notice it until `RepeatOption` came along. I think a more normal thing to do is to have `Option<int>` and then have the template derive a value policy from the input type.
This patch accomplishes that.
> Redo the argparser type system.

- amtl/am-string.h
**strcmpi** should be **_strcmpi**
> Fix A Warning — strcmpi @ am-string.h

- amtl/os/am-system-errors.h
strerror_r with char* return type is a GNU specific extension.
https://linux.die.net/man/3/strerror_r
> Fix build on non-Glibc systems

- .appveyor/build.bat
- .appveyor/setup_environment.bat
- .travis.yml
- README.md
- amtl/am-algorithm.h
- amtl/am-cxx.h
- amtl/am-moveable.h
- amtl/am-priority-queue.h
- amtl/experimental/am-argparser.h
- appveyor.yml
- tests/test-callable.cpp
- tests/test-threadlocal-threaded.cpp
- tests/test-threadlocal-unthreaded.cpp
This bumps the minimum compilers to GCC 4.9 (from 4.6), MSVC 2015 (from 2013), and Clang 3.4 (from 3.0). The workaround header (am-cxx.h) is much simpler now.
> Remove all existing compiler workarounds.

- AMBuildScript
- amtl/AMBuilder
- amtl/am-string.h
- amtl/experimental/am-argparser.cc
- amtl/experimental/am-argparser.h
- tests/AMBuild.tests
- tests/test-argparser.cpp
Support inline options as spcomp does, where -O2 and -O:2 are allowed.
Support slash options for spcomp compatibility.
Support unaccounted positionals.
Support global static arguments, and add a new libamtl AMBuilder snippet
for embedders to link the necessary support.
Fix some style problems missed by amrestyler while here.
> Improve the argument parser.

- README.md
- amtl/am-function.h
- amtl/experimental/am-argparser.h
- tests/AMBuild.tests
- tests/test-callable.cpp
Removing this was a little premature as it turns out SourceMod uses it
across module boundaries. We cannot use STL across module boundaries.
Instead, simplify this quite a bit. Remove FuncPtr (which was unused),
and rename Lambda to Function, removing the old Function implementation.
This makes it basically identical to std::function including the caveat
that captures must be copy constructable.
> Restore ke::Function.

- AMBuildScript
- README.md
- amtl/am-string.h
- amtl/am-vector.h
- amtl/experimental/am-argparser.h
- tests/test-argparser.cpp
- tests/test-hashmap.cpp
- tests/test-string.cpp
It's difficult to mix AString with third-party C++ code that uses
std::string. The only advantage AString provides is being able to
transfer ownership of the underlying buffer, but that is not enough to
warrant maintaining this half-implemented class.
> Remove AString and replace uses with std::string.

- amtl/am-priority-queue.h
- tests/test-priority-queue.cpp
Note that we did not replace this with STL's priority queue, as there is
no way to pop-and-move the top element.
> Use std::vector for PriorityQueue.

- .appveyor/build.bat
- .travis.yml
- checkout-deps.sh
- Checks for an active 'python'/'python3' command.
- Checks for an active pip installation in the detected Python installation, otherwise, it installs it via 'get-pip.py'
See: alliedmodders/ambuild#68
> Updated 'checkout-deps' to check for 'pip'/'pip3' prior to installing 'AMBuild'

- amtl/experimental/am-argparser.h
- tests/test-argparser.cpp
Even after encountering a StopOption, the parser would check if there are enough positional parameters leading to a different error message than what the implementor wanted for the StopOption.
> Fix argparser StopOption still requiring positional arguments

- .appveyor/build.bat
- .appveyor/setup_environment.bat
The pipeline is failing, I suspect it's because ambuild requires python 3.3 or higher, this changes .appveyor to use python 3.3 to build ambuild in the 'setup_environment.bat' 
https://github.com/alliedmodders/ambuild
https://www.appveyor.com/docs/windows-images-software/#python:~:text=Python%203.3.5%20x86%20(-,C%3A%5CPython33,-)
> Use python33 to build ambuild in appveyor

- amtl/am-string.h
Before fix it gives this error:
```
amtl/am-string.h:184:16: error: conversion function from 'std::nullptr_t' to 'std::string' (aka 'basic_string<char>') invokes a deleted function
184 |         return nullptr;
```
Returning an empty string fixes the problem and works as intended according to this:
> There are several possible ways to fix this code; you could pass an empty string with "" or std::string{} or even {} (depending on whether open_choices() is overloaded).
from https://github.com/mamedev/mame/issues/8265
> Fix compilation error with C++23
